name: CI

on: [push]

jobs:
  build_macOS:
    name: macOS
    runs-on: macos-13
    steps:
    - name: use python3.9
      run: |
        brew install python@3.9
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        ./build-desktop.sh macos x86_64
